# Generated by Django 3.1.6 on 2021-02-26 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0002_productcatalog_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(default=0, max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='productitem',
            name='category',
            field=models.ForeignKey(default=0, on_delete=models.SET(0), to='preyes_app.category'),
        ),
    ]
