# Generated by Django 3.1.6 on 2021-02-26 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0003_auto_20210226_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='retailer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='preyes_app.retailer'),
        ),
    ]
