# Generated by Django 3.1.6 on 2021-03-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0005_auto_20210226_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='product_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='productitem',
            name='specs_tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
