# Generated by Django 3.1.6 on 2021-03-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0006_auto_20210303_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='image_url',
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productitem',
            name='product_url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
