# Generated by Django 3.1.6 on 2021-03-03 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0007_auto_20210303_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
