# Generated by Django 3.1.6 on 2021-03-03 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0009_auto_20210303_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='specs_tag',
            field=models.TextField(blank=True),
        ),
    ]
