# Generated by Django 3.1.6 on 2021-03-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0010_auto_20210303_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='name',
            field=models.TextField(),
        ),
    ]
