# Generated by Django 3.1.6 on 2021-03-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0012_auto_20210303_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='category_preference',
            field=models.ManyToManyField(to='preyes_app.Category'),
        ),
    ]
