# Generated by Django 3.1.6 on 2021-03-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0014_auto_20210311_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_url', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
