# Generated by Django 3.1.6 on 2021-04-07 11:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0016_auto_20210325_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(default=datetime.datetime(2021, 4, 7, 11, 35, 57, 147302))),
                ('GUID', models.CharField(max_length=250)),
                ('email', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='preyes_app.customer')),
            ],
        ),
    ]
