# Generated by Django 3.1.6 on 2021-04-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0019_auto_20210407_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordchangerequest',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
