# Generated by Django 3.1.6 on 2021-04-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0020_passwordchangerequest_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
