# Generated by Django 3.1.6 on 2021-04-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0021_productitem_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='product_id',
            field=models.CharField(blank=True, default='0', max_length=255),
        ),
    ]
