# Generated by Django 3.1.6 on 2021-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0022_productitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetitem',
            name='target_price_type',
            field=models.CharField(choices=[('FX', 'Fixed price'), ('PC', 'Percentage price'), ('ALL', 'All discounts')], default='FX', max_length=3),
        ),
    ]
