# Generated by Django 3.1.6 on 2021-04-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0023_targetitem_target_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetitem',
            name='target_price_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage'), ('all_discount', 'All Discounts')], default='fixed', max_length=20),
        ),
    ]
