# Generated by Django 3.1.6 on 2021-04-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0024_auto_20210421_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetitem',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19),
        ),
    ]
