# Generated by Django 3.1.6 on 2021-04-28 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0026_productitem_last_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='last_updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 28, 14, 6, 6, 603306, tzinfo=utc)),
        ),
    ]
