# Generated by Django 3.1.6 on 2021-04-28 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0027_auto_20210428_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='last_updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
