# Generated by Django 3.1.6 on 2021-02-17 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('insertion', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('notifications', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_url', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('retailer_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TargetItem',
            fields=[
                ('productitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preyes_app.productitem')),
                ('target_price', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
            options={
                'abstract': False,
            },
            bases=('preyes_app.productitem',),
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_items', models.ManyToManyField(related_name='product_items', to='preyes_app.ProductItem')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('insertion', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('notifications', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
                ('target_list', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preyes_app.targetlist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='targetlist',
            name='target_items',
            field=models.ManyToManyField(related_name='target_items', to='preyes_app.TargetItem'),
        ),
        migrations.CreateModel(
            name='ProductNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time_stamp', models.DateTimeField()),
                ('target_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preyes_app.targetitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
