# Generated by Django 3.1.6 on 2021-02-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('insertion', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('notifications', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('insertion', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=100)),
                ('notifications', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('product_catalog_reference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='preyes_app.productcatalog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_url', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TargetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_reference', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='preyes_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='TargetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=10, max_digits=19)),
                ('product_item_reference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='preyes_app.productitem')),
                ('target_list_reference', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='preyes_app.targetlist')),
            ],
        ),
        migrations.CreateModel(
            name='ProductNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('time_stamp', models.DateTimeField()),
                ('target_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='preyes_app.targetitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='productitem',
            name='retailer_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='preyes_app.retailer'),
        ),
    ]
