# Generated by Django 3.1.6 on 2021-02-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preyes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcatalog',
            name='name',
            field=models.CharField(default='preyes catalog', max_length=100),
        ),
    ]
